rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database hyperspace_test;' -U postgres
test:
  adapter: postgresql
  database: hyperspace_test
